export const qualityHtmlExample = `<section class="rounded-2xl bg-[#f4f7fb] p-4 sm:p-5">
  <div class="mx-auto grid max-w-[980px] grid-cols-1 gap-4 lg:grid-cols-2">
    <article class="flex h-full flex-col rounded-xl border border-[#d9e1e8] bg-white p-4 shadow-[0_3px_12px_rgba(27,58,87,.06)]">
      <div class="mb-3 flex items-start justify-between gap-3"><div class="inline-flex items-center gap-1.5 rounded-md border border-[#e2e8ee] bg-[#f7f9fb] px-2.5 py-1.5 text-[10px] font-semibold text-[#526a80]"><span class="text-blue-600">◆</span>Gestión de Calidad</div><span class="inline-flex items-center gap-1.5 rounded-full border border-blue-200 bg-blue-50 px-2.5 py-1 text-[10px] font-semibold text-blue-700"><span class="h-1.5 w-1.5 rounded-full bg-blue-500"></span>En Progreso</span></div>
      <h2 class="mb-2 text-[15px] font-bold leading-snug tracking-tight text-[#20394e]">Tasa de finalización de las clases inferior al 80%</h2>
      <div class="mb-3 rounded-lg border border-[#e3e9ee] bg-[#f8fafc] p-3"><div class="mb-2.5 flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wide text-emerald-700"><span class="flex h-4 w-4 items-center justify-center rounded-full bg-emerald-500 text-[10px] text-white">✓</span>Acciones realizadas (4)</div><ul class="space-y-2 text-[11px] leading-relaxed text-[#526a80]"><li class="flex items-start gap-2"><span class="font-bold text-emerald-600">✓</span><span>Matriz para consolidar tasa de finalización diaria por parte del director.</span></li><li class="flex items-start gap-2"><span class="font-bold text-emerald-600">✓</span><span>Piloto de llamadas del Call Center a familias.</span></li><li class="flex items-start gap-2"><span class="font-bold text-emerald-600">✓</span><span>Listado de niños para Remediación entregado a directores.</span></li><li class="flex items-start gap-2"><span class="font-bold text-emerald-600">✓</span><span>Capacitación en Teacha a líderes de Calidad.</span></li></ul></div>
      <div class="mt-auto rounded-lg border border-yellow-200 bg-yellow-50/70 p-3"><div class="mb-1.5 flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wide text-yellow-700"><span class="flex h-4 w-4 items-center justify-center rounded-full border-2 border-yellow-500 text-[9px]">◎</span>Acción requerida para cierre</div><p class="text-[11px] leading-relaxed text-[#526a80]">Creación de tablero para monitoreo por parte del director.</p></div>
    </article>
    <article class="flex h-full flex-col rounded-xl border border-[#d9e1e8] bg-white p-4 shadow-[0_3px_12px_rgba(27,58,87,.06)]">
      <div class="mb-3 flex items-start justify-between gap-3"><div class="inline-flex items-center gap-1.5 rounded-md border border-[#e2e8ee] bg-[#f7f9fb] px-2.5 py-1.5 text-[10px] font-semibold text-[#526a80]"><span class="text-blue-600">◆</span>Gestión de Calidad</div><span class="inline-flex items-center gap-1.5 rounded-full border border-yellow-200 bg-yellow-50 px-2.5 py-1 text-[10px] font-semibold text-yellow-700"><span class="h-1.5 w-1.5 rounded-full bg-yellow-500"></span>Pendiente</span></div>
      <h2 class="mb-2 text-[15px] font-bold leading-snug tracking-tight text-[#20394e]">Clase de Refuerzo desfasada respecto a la programación académica estandarizada.</h2>
      <div class="mb-3 rounded-lg border border-[#e3e9ee] bg-[#f8fafc] p-3"><div class="mb-2.5 flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wide text-emerald-700"><span class="flex h-4 w-4 items-center justify-center rounded-full bg-emerald-500 text-[10px] text-white">✓</span>Acciones realizadas (1)</div><ul class="space-y-2 text-[11px] leading-relaxed text-[#526a80]"><li class="flex items-start gap-2"><span class="font-bold text-emerald-600">✓</span><span>Enunciar explícitamente en el plan de mejora la alineación de fechas y objetivos por módulo.</span></li></ul></div>
      <div class="mt-auto rounded-lg border border-yellow-200 bg-yellow-50/70 p-3"><div class="mb-1.5 flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wide text-yellow-700"><span class="flex h-4 w-4 items-center justify-center rounded-full border-2 border-yellow-500 text-[9px]">◎</span>Acción requerida para cierre</div><p class="text-[11px] leading-relaxed text-[#526a80]">Capacitación con docentes de refuerzo para fortalecer el proceso de implementación.</p></div>
    </article>
  </div>
</section>`;
