"use client";
import { ClipboardCheck } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useAuditFilters } from "@/stores/AuditFiltersContext";
import { attendanceData } from "./schoolData";
export default function AttendanceChart() {
    const { platforms } = useAuditFilters();
    return <div className="mt-5 rounded-lg border border-[#d7e0e9] bg-white p-4"><div className="flex items-start justify-between"><div><h3 className="text-[10px] font-semibold text-[#263e54]">Asistencia diaria</h3><p className="mt-1 text-[8px] text-[#91a3b7]">Evolución diaria por plataforma</p></div><ClipboardCheck className="h-4 w-4 text-[#8ea4ba]"/></div><div className="mt-2 flex gap-4 text-[8px] text-[#50677d]">{platforms.includes("KIRA") && <span><i className="mr-1.5 inline-block h-2.5 w-2.5 rounded-full bg-[#1771d2]"/>KIRA</span>}{platforms.includes("IHFB") && <span><i className="mr-1.5 inline-block h-2.5 w-2.5 rounded-full bg-[#7044f4]"/>IHFB</span>}</div><div className="mt-2 h-[250px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={attendanceData} margin={{ top: 10, right: 10, bottom: 0, left: -20 }}><CartesianGrid stroke="#e8eef4" strokeDasharray="2 3" vertical={false}/><XAxis dataKey="day" tickLine={false} axisLine={false} fontSize={9}/><YAxis domain={[80, 100]} ticks={[80, 85, 90, 95, 100]} tickFormatter={(value) => `${value}%`} tickLine={false} axisLine={false} fontSize={8}/><Tooltip formatter={(value) => `${value}%`}/>{platforms.includes("KIRA") && <Line type="monotone" dataKey="kira" name="KIRA" stroke="#1671d3" strokeWidth={2.5} dot={{ r: 4, fill: "#1671d3", strokeWidth: 0 }}/>}{platforms.includes("IHFB") && <Line type="monotone" dataKey="ihfb" name="IHFB" stroke="#7044f4" strokeWidth={2.5} dot={{ r: 4, fill: "#7044f4", strokeWidth: 0 }}/>}</LineChart></ResponsiveContainer></div></div>;
}
