"use client";
import { useState } from "react";
import { CheckCircle2, Eye, MessageCircleQuestion, Reply, Send, XCircle } from "lucide-react";
import { dashboardDatabase } from "@/data/dashboardDatabase";
import { useDashboardData } from "@/stores/DashboardDataContext";
type CampaignValue = number | string;
type Campaign = { name: CampaignValue; date: CampaignValue; tipoRespuesta: CampaignValue; mensajesNoEnviados: CampaignValue; mensajesEnviados: CampaignValue; mensajesEntregados: CampaignValue; leidos: CampaignValue; respuestasRecibidas: CampaignValue };
const metrics = [["Tipo de respuesta", "tipoRespuesta", MessageCircleQuestion, "text-[#176dcc]"], ["Mensajes no enviados", "mensajesNoEnviados", XCircle, "text-[#dc3d3d]"], ["Mensajes enviados", "mensajesEnviados", Send, "text-[#176dcc]"], ["Mensajes entregados", "mensajesEntregados", CheckCircle2, "text-[#168642]"], ["Leídos", "leidos", Eye, "text-[#7b3ff2]"], ["Respuestas recibidas", "respuestasRecibidas", Reply, "text-[#e77b13]"]] as const;
function hasData(value: unknown): boolean { if (value === null || value === undefined || value === "" || value === 0 || value === false) return false; if (typeof value === "string") return value.trim().length > 0; if (Array.isArray(value)) return value.some(hasData); if (typeof value === "object") return Object.values(value as Record<string, unknown>).some(hasData); return true; }
function campaignValue(value: unknown): CampaignValue { return typeof value === "number" || typeof value === "string" ? value : ""; }
function campaignList(value: unknown): Campaign[] { if (!Array.isArray(value)) return []; return value.filter((item): item is Record<string, unknown> => Boolean(item) && typeof item === "object" && !Array.isArray(item)).map((item) => ({ name: campaignValue(item.nombre ?? item.name), date: campaignValue(item.fecha ?? item.date), tipoRespuesta: campaignValue(item.tipoRespuesta), mensajesNoEnviados: campaignValue(item.mensajesNoEnviados), mensajesEnviados: campaignValue(item.mensajesEnviados), mensajesEntregados: campaignValue(item.mensajesEntregados), leidos: campaignValue(item.leidos), respuestasRecibidas: campaignValue(item.respuestasRecibidas) })); }
function campaignGroups(value: unknown) { if (Array.isArray(value)) return { directors: campaignList(value), teachers: [] }; if (!value || typeof value !== "object") return { directors: [], teachers: [] }; const groups = value as Record<string, unknown>; return { directors: campaignList(groups.directores), teachers: campaignList(groups.docentes) }; }
function CampaignSection({ title, campaigns }: { title: string; campaigns: Campaign[] }) { return <><h2 className="mt-6 text-[13px] font-semibold uppercase tracking-[.08em] text-[#29455f]">{title}</h2>{!campaigns.length ? <div className="mt-4 rounded-xl border border-dashed border-[#d9e1e8] bg-white px-4 py-8 text-center text-[11px] text-[#8ea1b5]">No hay campañas para esta categoría.</div> : <div className="mt-4 grid grid-cols-1 gap-4 lg:grid-cols-3">{campaigns.map((campaign, index) => <article key={`${title}-${String(campaign.name)}-${index}`} className="rounded-xl border border-[#d9e1e8] bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><h3 className="text-[12px] font-semibold text-[#29455f]">{campaign.name}</h3><p className="text-right text-[9px] text-[#8ea1b5]">{campaign.date}</p></div><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2">{metrics.map(([label, key, Icon, color], metricIndex) => <div key={key} className="min-w-0 rounded-md bg-[#f8fafc] px-3 py-2"><span className="flex min-w-0 items-center gap-1.5 text-[8px] text-[#71869a]"><Icon className={`h-3.5 w-3.5 shrink-0 ${color}`}/><span className="truncate">{label}</span></span><span className={`mt-2 block truncate text-[11px] font-semibold ${metricIndex === 0 ? "text-[#176dcc]" : "text-[#29455f]"}`}>{campaign[key]}</span></div>)}</div></article>)}</div>}</>; }
export default function CampaignsNerdsPanel() { useDashboardData(); const source = dashboardDatabase.gestionEscolar?.gestionOperativa?.campanasNerds; const groups = campaignGroups(source); const [activeGroup, setActiveGroup] = useState<"directors" | "teachers">(groups.directors.length ? "directors" : "teachers"); if (!hasData(source)) return <section className="mt-8"><h2 className="text-[15px] font-semibold tracking-[.04em] text-[#29455f]">CAMPAÑAS NERDS</h2><div className="mt-4 rounded-xl border border-dashed border-[#d9e1e8] bg-white px-4 py-8 text-center text-[11px] text-[#8ea1b5]">No hay información de campañas para esta fecha.</div></section>; const title = activeGroup === "directors" ? "DIRECTORES" : "DOCENTES"; const campaigns = activeGroup === "directors" ? groups.directors : groups.teachers; return <section className="mt-8"><h2 className="text-[15px] font-semibold tracking-[.04em] text-[#29455f]">CAMPAÑAS NERDS</h2><div className="mt-4 inline-flex rounded-lg border border-[#d9e1e8] bg-white p-1 shadow-sm"><button type="button" onClick={() => setActiveGroup("directors")} disabled={!groups.directors.length} className={`rounded-md px-4 py-1.5 text-[10px] font-semibold transition ${activeGroup === "directors" ? "bg-[#eaf3ff] text-[#176dcc]" : "text-[#6f8294] hover:bg-[#f5f8fb]"} disabled:cursor-not-allowed disabled:opacity-40`}>Directores{groups.directors.length ? ` (${groups.directors.length})` : ""}</button><button type="button" onClick={() => setActiveGroup("teachers")} disabled={!groups.teachers.length} className={`rounded-md px-4 py-1.5 text-[10px] font-semibold transition ${activeGroup === "teachers" ? "bg-[#f2ecff] text-[#7b3ff2]" : "text-[#6f8294] hover:bg-[#f5f8fb]"} disabled:cursor-not-allowed disabled:opacity-40`}>Docentes{groups.teachers.length ? ` (${groups.teachers.length})` : ""}</button></div><CampaignSection title={title} campaigns={campaigns} /></section>; }
