"use client";

import { useState, type ReactNode } from "react";
import Link from "./BackToSchoolSection";
import { ClipboardCheck, Layers3, TrendingUp } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { observationsData, trainingData } from "./operationalData";

type Tab="observaciones"|"formacion";
export default function OperationalManagementPage(){const[tab,setTab]=useState<Tab>("observaciones");return <main className="min-h-screen bg-[#f5f8fc]"><div className="mx-auto max-w-[1020px] px-4 pb-16 pt-6"><div className="flex items-start justify-between"><div><h1 className="text-sm font-semibold tracking-[.04em] text-[#263e54]">GESTIÓN OPERATIVA</h1><p className="mt-1 text-[8px] text-[#8fa1b5]">Seguimiento de observaciones y formación de directores</p></div><Link href="/#gestion-escolar" className="rounded-md border border-[#d4dde6] bg-white px-3 py-1.5 text-[8px] text-[#60758a]">← Volver</Link></div><div className="mt-4 flex flex-wrap gap-2">{[["observaciones","Observaciones de clases"],["formacion","Formación de directores"]].map(([value,label])=><button key={value} onClick={()=>setTab(value as Tab)} className={`h-[29px] rounded-md border bg-white px-3 text-[8px] ${tab===value?"border-[#1976d2] text-[#176dca]":"border-[#d6dfe8] text-[#596f83]"}`}>{label}</button>)}</div><div className="mt-4">{tab==="observaciones"&&<Panel title="Observaciones de clases de directores" subtitle="Seguimiento de directores activos, observaciones y realimentaciones"><Metrics items={[["Directores activos","859","Directores activos registrados","blue"],["Observaciones realizadas","803","Clases observadas","green"],["Realimentaciones","745","Realimentaciones realizadas","purple"]]}/><Chart data={observationsData} color="#7142ee" max={180}/></Panel>}{tab==="formacion"&&<Panel title="Formación de directores" subtitle="Directores formados del universo y distribución por bloque"><Metrics items={[["Directores formados","1997","Total de registros de formación","blue"],["Bloques","5","Bloques con registros de formación","purple"]]}/><Chart data={trainingData} color="#1c70c9" max={600}/></Panel>}</div></div></main>}
function Panel({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <section className="overflow-hidden rounded-lg border border-[#d8e0e8] bg-white"><div className="px-4 py-4"><h2 className="text-[10px] font-semibold text-[#263e53]">{title}</h2><p className="mt-1 text-[8px] text-[#8fa1b5]">{subtitle}</p></div>{children}</section>}
function Metrics({items}:{items:string[][]}){const colors:Record<string,string>={blue:"text-[#176dcc] bg-[#eaf3ff]",green:"text-[#178742] bg-[#eaf8ef]",purple:"text-[#7040ef] bg-[#f2ecff]"};return <div className="grid gap-3 border-t p-4 md:grid-cols-3">{items.map(([title,value,description,type])=>{const Icon=title==="Bloques"?Layers3:title==="Realimentaciones"?TrendingUp:ClipboardCheck;return <article key={title} className="min-h-[113px] rounded-lg border border-[#dce3ea] p-4"><div className="flex items-center gap-3"><span className={`flex h-7 w-7 items-center justify-center rounded-md ${colors[type]}`}><Icon className="h-4 w-4"/></span><p className="text-[8px] font-semibold uppercase text-[#586f83]">{title}</p></div><p className={`mt-4 text-[25px] font-medium ${colors[type].split(" ")[0]}`}>{value}</p><p className="mt-3 text-[8px] text-[#91a2b5]">{description}</p></article>})}</div>}
function Chart({data,color,max}:{data:{block:string;value:number}[];color:string;max:number}){return <div className="h-[250px] px-4 pb-4 pt-5"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{top:10,right:15,left:-20}}><CartesianGrid stroke="#e8edf3" strokeDasharray="2 3" vertical={false}/><XAxis dataKey="block" axisLine={false} tickLine={false} fontSize={9}/><YAxis domain={[0,max]} axisLine={false} tickLine={false} fontSize={8}/><Tooltip/><Bar dataKey="value" fill={color} barSize={20} radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div>}
