"use client";

import Link from "./BackToSchoolSection";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { projectSchoolsChart, projectSchoolsTable } from "./projectSchoolsData";

export default function ProjectSchoolsPage() {
  return <main className="min-h-screen bg-[#f5f8fc]"><div className="mx-auto w-full max-w-[1020px] px-4 pb-16 pt-6"><div className="flex items-start justify-between"><div><h1 className="text-sm font-semibold tracking-[.04em] text-[#263e54]">CENTROS ESCOLARES DEL PROYECTO</h1><p className="mt-1 text-[8px] text-[#8fa1b5]">Distribución de centros por bloque, fase y estado operativo</p></div><Link href="/?view=gestion-escolar" className="rounded-md border border-[#d4dde6] bg-white px-3 py-1.5 text-[8px] text-[#60758a]">← Volver</Link></div><div className="mt-5 grid grid-cols-1 gap-4 lg:grid-cols-2"><section className="min-h-[580px] rounded-lg border border-[#d8e0e8] bg-white p-4"><h2 className="text-[10px] font-semibold text-[#253d52]">Centros por bloque y fase</h2><p className="mt-1 text-[8px] text-[#8fa1b5]">Consulta detallada de centros del proyecto</p><div className="mt-5 h-[240px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={projectSchoolsChart} margin={{ top: 10, right: 10, bottom: 35, left: -20 }}><CartesianGrid stroke="#e7edf3" strokeDasharray="2 3" vertical={false} /><XAxis dataKey="name" angle={-38} textAnchor="end" interval={0} height={65} axisLine={false} tickLine={false} fontSize={6} /><YAxis domain={[0,120]} ticks={[0,30,60,90,120]} axisLine={false} tickLine={false} fontSize={7} /><Tooltip /><Bar dataKey="value" fill="#1d70c8" barSize={15} radius={[2,2,0,0]} /></BarChart></ResponsiveContainer></div></section><section className="overflow-hidden rounded-lg border border-[#d8e0e8] bg-white"><div className="p-4"><h2 className="text-[10px] font-semibold text-[#253d52]">Detalle de centros</h2><p className="mt-1 text-[8px] text-[#8fa1b5]">Distribución por bloque, fase y estado</p></div><div className="overflow-x-auto"><table className="w-full border-collapse"><thead><tr className="border-y bg-[#f8fafc]">{["Bloque","Fase","Estado","CE"].map((item) => <th key={item} className="px-4 py-3 text-left text-[7px] uppercase text-[#8294a7] last:text-right">{item}</th>)}</tr></thead><tbody>{projectSchoolsTable.map(([block,phase,status,value],index) => <tr key={`${block}-${phase}-${status}-${index}`} className="border-b border-[#e2e8ee]"><td className="px-4 py-[11px] text-[8px] font-semibold">{block}</td><td className="px-4 py-[11px] text-[8px] text-[#62768a]">{phase}</td><td className="px-4 py-[11px]"><Status status={status} /></td><td className="px-4 py-[11px] text-right text-[8px] font-semibold">{value}</td></tr>)}</tbody></table></div></section></div></div></main>;
}

function Status({ status }: { status: string }) { const styles: Record<string,string> = { Activo: "bg-[#ddf6e6] text-[#24904c]", Pausa: "bg-[#fff0c8] text-[#de9000]", Sustituto: "bg-[#e6f0ff] text-[#2872cb]" }; return <span className={`rounded-full px-2 py-1 text-[7px] font-semibold ${styles[status]}`}>{status}</span>; }
