"use client";

import { useMemo, type ReactNode } from "react";

type ProgressItem={label:string;value:number;percentage:number};
const observationData:ProgressItem[]=[{label:"Directores Activos",value:162,percentage:42.3},{label:"Observaciones Realizadas",value:467,percentage:24.4},{label:"Realimentaciones Realizadas",value:245,percentage:12.8}];
const trainingData:ProgressItem[]=[{label:"Grupo 1",value:183,percentage:99.7},{label:"Grupo 2",value:196,percentage:100},{label:"Grupo 3",value:192,percentage:96.5},{label:"Grupo 4",value:198,percentage:98.5},{label:"Grupo 5",value:189,percentage:94.5}];
const scheduleG12:ProgressItem[]=[{label:"CE Verificados/Aprobados",value:383,percentage:100}];
const scheduleG345:ProgressItem[]=[{label:"CE Verificados/Aprobados",value:555,percentage:92.5},{label:"Con observaciones",value:25,percentage:4.2},{label:"Casos especiales",value:5,percentage:.8},{label:"No aplica",value:1,percentage:.2},{label:"Nuevos centros escolares",value:14,percentage:2.3}];

export default function SchoolManagementActivities(){const totalTraining=useMemo(()=>trainingData.reduce((sum,item)=>sum+item.value,0),[]);return <section className="bg-[#f7f9fc] px-4 py-6 text-[#15213b] sm:px-6 sm:py-8"><div className="mx-auto max-w-[1180px]"><div className="mb-6"><h1 className="text-[24px] font-semibold tracking-[-.03em] text-[#1f295d] sm:text-[28px]">Gestión Escolar</h1><p className="mt-1 text-[12px] text-[#748197] sm:text-[14px]">Principales actividades de los grupos 1, 2, 3, 4 y 5</p></div><div className="rounded-[18px] border border-[#e1e7ee] bg-white p-4 shadow-[0_8px_30px_rgba(27,42,75,.04)] sm:p-6"><div className="mb-7 flex flex-wrap items-center justify-between gap-3 border-b border-[#edf1f5] pb-5"><div><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#8a97a8]">Periodo</p><p className="mt-1 text-[17px] font-semibold text-[#1d2849]">10/08/2026 — 12/08/2026</p></div><span className="rounded-full bg-[#f1f4ff] px-4 py-2 text-[11px] font-medium text-[#36428a]">Seguimiento operativo</span></div><div className="grid gap-6 xl:grid-cols-2"><div className="space-y-6"><Card><SectionHeader eyebrow="G1 y G2" title="Observación y realimentación de clases" subtitle="Seguimiento de directores y actividades de observación"/><div className="mt-5 space-y-4">{observationData.map(item=><ProgressRow key={item.label}{...item} color="navy"/>)}</div><Actions items={["Llamadas de monitoreo a directores de G1 y G2.","Capacitación de Técnicos de Gestión Escolar en el uso del aplicativo de observación.","Técnicos del SDP solucionan las incidencias del aplicativo de observación."]}/></Card><Card><SectionHeader eyebrow="Eje 1 y 2" title="Formación de directores" subtitle={`${totalTraining} participaciones registradas`}/><div className="mt-5 space-y-3">{trainingData.map(item=><ProgressRow key={item.label}{...item} color="navy" compact/>)}</div></Card></div><div className="space-y-6"><Card><SectionHeader eyebrow="G1 y G2" title="Validación de horarios" subtitle="Centros escolares verificados y aprobados"/><div className="mt-5">{scheduleG12.map(item=><ProgressRow key={item.label}{...item} color="blue"/>)}</div></Card><Card><SectionHeader eyebrow="G3, G4 y G5" title="Validación de horarios" subtitle="Estado de revisión de centros escolares"/><div className="mt-5 space-y-4">{scheduleG345.map((item,index)=><ProgressRow key={item.label}{...item} color={index===0?"blue":"slate"} compact={index!==0}/>)}</div><Actions items={["Videollamadas con el director para ajustar el horario escolar.","Monitoreo diario por medio de WhatsApp."]}/></Card></div></div></div></div></section>}
function Card({children}:{children:ReactNode}){return <article className="rounded-[16px] border border-[#e2e8ef] bg-white p-5">{children}</article>}
function SectionHeader({eyebrow,title,subtitle}:{eyebrow:string;title:string;subtitle:string}){return <div><span className="inline-flex rounded-full bg-[#f1f4ff] px-2.5 py-1 text-[9px] font-semibold uppercase tracking-[.08em] text-[#5968a7]">{eyebrow}</span><h2 className="mt-3 text-[17px] font-semibold text-[#1d2849]">{title}</h2><p className="mt-1 text-[11px] text-[#8995a6]">{subtitle}</p></div>}
function Actions({items}:{items:string[]}){return <div className="mt-6 rounded-[12px] bg-[#f8fafc] p-4"><p className="text-[10px] font-semibold uppercase tracking-wide text-[#7f8ba0]">Acciones G1–G5</p><ul className="mt-3 space-y-2 text-[12px] leading-5 text-[#68758a]">{items.map(item=><li key={item} className="flex gap-2"><span className="mt-[8px] h-1.5 w-1.5 shrink-0 rounded-full bg-[#6271a8]"/>{item}</li>)}</ul></div>}
function ProgressRow({label,value,percentage,color,compact=false}:{label:string;value:number;percentage:number;color:"navy"|"blue"|"slate";compact?:boolean}){const colors={navy:"bg-[#25265f]",blue:"bg-[#315fcb]",slate:"bg-[#69758b]"};const percentageColor={navy:"text-[#25265f]",blue:"text-[#315fcb]",slate:"text-[#68758a]"};return <div><div className="mb-2 flex items-center justify-between gap-4"><span className={`font-medium text-[#2b3556] ${compact?"text-[12px]":"text-[13px]"}`}>{label}</span><div className="flex items-center gap-3"><span className="text-[13px] font-semibold text-[#17223d]">{value}</span><span className={`min-w-[48px] text-right text-[11px] font-semibold ${percentageColor[color]}`}>{percentage}%</span></div></div><div className={`overflow-hidden rounded-full bg-[#edf1f5] ${compact?"h-2":"h-2.5"}`}><div className={`h-full rounded-full ${colors[color]}`} style={{width:`${Math.min(percentage,100)}%`}}/></div></div>}
