import { BookOpen } from "lucide-react";
import type { LineProgress } from "./learningData";

const accent = { blue:{icon:"text-[#1771d3]",bg:"bg-[#eaf3ff]"},purple:{icon:"text-[#7544f4]",bg:"bg-[#f2ecff]"},green:{icon:"text-[#198849]",bg:"bg-[#eaf8ef]"} };
export default function LineProgressCard({ item }: { item: LineProgress }) {
  const colors = accent[item.accent];
  return <article className="overflow-hidden rounded-lg border border-[#d8e0e8] bg-white"><div className="flex items-center justify-between border-b border-[#e4e9ef] px-4 py-3"><div className="flex items-center gap-3"><span className={`flex h-7 w-7 items-center justify-center rounded-md ${colors.bg}`}><BookOpen className={`h-4 w-4 ${colors.icon}`} /></span><div><p className="text-[7px] font-semibold uppercase text-[#8194a7]">Línea / aplicativo</p><h3 className="mt-1 text-[13px] font-semibold text-[#223b50]">{item.name}</h3></div></div><span className={`rounded-full px-2 py-1 text-[6px] font-semibold uppercase ${colors.bg} ${colors.icon}`}>Contenido</span></div><div className="space-y-5 px-4 py-4"><Progress label="Autoría" value={item.authoring} range={item.authoringRange} color="bg-[#1971d1]" text="text-[#126fd0]" /><Progress label="Producción / edición" value={item.production} range={item.productionRange} color="bg-[#7544f4]" text="text-[#7544f4]" /><Progress label="Publicación" value={item.publication} range={item.publicationRange} color="bg-[#168642]" text="text-[#168642]" /></div></article>;
}
function Progress({ label,value,range,color,text }: { label:string;value:number;range:string;color:string;text:string }) { return <div><div className="flex items-center justify-between"><span className="text-[8px] font-medium text-[#41596e]">{label}</span><span className={`text-[17px] font-medium ${text}`}>{value}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#e9eef4]"><div className={`h-full rounded-full ${color}`} style={{width:`${value}%`}} /></div><div className="mt-2 flex justify-between"><span className="text-[7px] text-[#9aabbd]">Clases</span><span className="text-[8px] font-medium text-[#43596d]">{range}</span></div></div>; }
