"use client";
import BarreraCard from "./BarreraCard";
import { useDashboardData } from "@/stores/DashboardDataContext";
import { getEvaluacion, tieneNumero } from "./evaluationViewData";
const colors=["#e5252a","#f05b0b","#f2a312","#19a97a","#0c7f73"];
const segments=(values:number[])=>values.map((value,index)=>({value,color:colors[index%colors.length]}));
export default function EvaluationComparison(){useDashboardData();const data=getEvaluacion().comparativasPorMateria??{};return <section className="space-y-4"><div className="grid grid-cols-1 gap-3 md:grid-cols-2">{Object.entries(data).map(([materia,item])=>tieneNumero(item.promedio)?<Average key={materia} title={`PROMEDIO ${materia.toUpperCase()}`} value={item.promedio} variation={item.variacionRespectoJunio}/>:null)}</div><div className="grid grid-cols-1 gap-4 xl:grid-cols-2">{Object.entries(data).map(([materia,item])=>(item.porcentajesJunio.length||item.porcentajesJulio.length)?<Comparison key={materia} title={`${materia[0].toUpperCase()+materia.slice(1)} - Comparativa por Niveles`} june={item.porcentajesJunio} july={item.porcentajesJulio}/>:null)}</div><BarreraCard/></section>;}
function Average({title,value,variation}:{title:string;value:number;variation:number|null}){return <article className="rounded-[9px] border border-[#dce3ea] bg-white p-5"><p className="text-[11px] font-semibold uppercase text-[#6b7f92]">{title}</p><div className="mt-3 flex items-center gap-2"><strong className="text-[25px] text-[#263d52]">{value}</strong><span className="rounded bg-[#fff0d7] px-2 py-1 text-[10px] font-semibold text-[#dd8d15]">Medio</span></div>{tieneNumero(variation)&&<p className="mt-2 text-[10px] text-[#e04444]">↘ {variation} vs Junio</p>}</article>}
function Comparison({title,june,july}:{title:string;june:number[];july:number[]}){return <article className="rounded-[8px] border border-[#dce4ec] bg-white p-4"><h3 className="text-[13px] font-semibold text-[#334b60]">{title}</h3><p className="mt-1 text-[10px] text-[#8a9daf]">Porcentaje de estudiantes en cada nivel</p><div className="mt-4 rounded-[7px] border bg-[#fbfcfd] p-3"><Row label="Junio" values={june}/><div className="my-3 border-t"/><Row label="Julio" values={july}/><div className="mt-3 flex justify-between pl-[42px] text-[7px] text-[#667b8e]"><span>CRÍTICO (0-35)</span><span>EXCELENTE (66-100)</span></div></div></article>}
function Row({label,values}:{label:string;values:number[]}){return <div className="flex items-center gap-2"><span className="w-[34px] text-[9px]">{label}</span><div className="flex h-[25px] flex-1 overflow-hidden rounded">{segments(values).map((item,index)=><div key={index} className="flex items-center justify-center text-[7px] font-semibold text-white" style={{width:`${item.value}%`,background:item.color}}>{item.value}%</div>)}</div></div>}
