import { BookOpen, School, TrendingUp, Users } from "lucide-react";

type Props = { title:string;accent:"blue"|"purple";schoolPercentage:number;schoolUniverse:string;schoolApplied:string;schoolPending:string;enrollmentPercentage:number;enrollmentUniverse:string;enrollmentApplied:string;enrollmentPending:string };

export default function TestCard(props: Props) {
  const blue = props.accent === "blue";
  return <section className={`overflow-hidden rounded-lg border border-[#d8e0e8] border-t-2 ${blue?"border-t-[#1671d3]":"border-t-[#7446ef]"} bg-white`}>
    <div className="flex items-center border-b px-4 py-3"><span className="flex h-7 w-7 items-center justify-center rounded-md bg-[#edf4fb]">{blue?<BookOpen className="h-4 w-4 text-[#1771d3]"/>:<TrendingUp className="h-4 w-4 text-[#7544f4]"/>}</span><div className="ml-3"><h3 className="text-[13px] font-semibold text-[#223c52]">{props.title}</h3><p className="mt-1 text-[7px] text-[#8d9fb1]">Avance de aplicación</p></div></div>
    <div className="grid gap-3 p-4 md:grid-cols-2"><Panel title="Centros escolares" icon={<School className="h-4 w-4"/>} percentage={props.schoolPercentage} applied={props.schoolApplied} pending={props.schoolPending} universe={props.schoolUniverse} blue={blue}/><Panel title="Matrícula" icon={<Users className="h-4 w-4"/>} percentage={props.enrollmentPercentage} applied={props.enrollmentApplied} pending={props.enrollmentPending} universe={props.enrollmentUniverse} blue={blue}/></div>
  </section>;
}
function Panel({title,icon,percentage,applied,pending,universe,blue}:{title:string;icon:React.ReactNode;percentage:number;applied:string;pending:string;universe:string;blue:boolean}) { const color=blue?"#1771d3":"#7544f4"; const pendingPercentage=Number((100-percentage).toFixed(2)); return <div className="rounded-lg border border-[#dce3ea] p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-md bg-[#eef4fb] text-[#4978a3]">{icon}</span><div><p className="text-[10px] font-semibold text-[#354e63]">{title}</p><p className="mt-1 text-[7px] uppercase text-[#8194a6]">Aplicación registrada</p></div></div><span className="rounded-full bg-[#edf5ff] px-2 py-1 text-[7px] font-semibold" style={{color}}>{percentage}% aplicado</span></div><div className="mt-4 flex items-center gap-5"><Ring percentage={percentage} color={color}/><div className="flex-1"><p className="text-[7px] uppercase text-[#8194a6]">Aplicados</p><p className="mt-1 text-2xl font-medium" style={{color}}>{applied}</p><p className="mt-2 text-[7px] text-[#8d9faf]">de {universe} del universo</p><div className="mt-3 rounded-md bg-[#ffe1e1] px-3 py-2 text-[#ef3434]"><div className="flex justify-between text-[7px] font-semibold"><span>Pendiente</span><span>{pendingPercentage}%</span></div><p className="mt-1 text-base font-semibold">{pending}</p></div></div></div></div>; }
function Ring({percentage,color}:{percentage:number;color:string}) { return <div className="flex h-[95px] w-[95px] shrink-0 items-center justify-center rounded-full" style={{background:`conic-gradient(${color} ${percentage}%, #e5edf6 0)`}}><div className="flex h-[72px] w-[72px] flex-col items-center justify-center rounded-full bg-white"><strong style={{color}}>{percentage}%</strong><span className="text-[7px]">aplicado</span></div></div>; }
